/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.item.impl.jooq.generation.tables.records;


import com.wuda.foundation.item.impl.jooq.generation.tables.ItemCategory;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * 物品分类
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemCategoryRecord extends UpdatableRecordImpl<ItemCategoryRecord> implements Record7<ULong, ULong, LocalDateTime, ULong, LocalDateTime, ULong, ULong> {

    private static final long serialVersionUID = -158175284;

    /**
     * Setter for <code>foundation_item.item_category.item_category_id</code>. 一定和【tree_node.tree_node_id】相等，因为实际表示树形结构的数据在tree_node表中，这里只是对tree_node的引用。tree_node表负责树形结构的维护，这里维护树形结构以外的内容，比如store_id字段用于维护归属。
     */
    public void setItemCategoryId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>foundation_item.item_category.item_category_id</code>. 一定和【tree_node.tree_node_id】相等，因为实际表示树形结构的数据在tree_node表中，这里只是对tree_node的引用。tree_node表负责树形结构的维护，这里维护树形结构以外的内容，比如store_id字段用于维护归属。
     */
    public ULong getItemCategoryId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>foundation_item.item_category.store_id</code>. 所属店铺ID
     */
    public void setStoreId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>foundation_item.item_category.store_id</code>. 所属店铺ID
     */
    public ULong getStoreId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>foundation_item.item_category.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>foundation_item.item_category.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>foundation_item.item_category.create_user_id</code>.
     */
    public void setCreateUserId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>foundation_item.item_category.create_user_id</code>.
     */
    public ULong getCreateUserId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>foundation_item.item_category.last_modify_time</code>.
     */
    public void setLastModifyTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>foundation_item.item_category.last_modify_time</code>.
     */
    public LocalDateTime getLastModifyTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>foundation_item.item_category.last_modify_user_id</code>.
     */
    public void setLastModifyUserId(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>foundation_item.item_category.last_modify_user_id</code>.
     */
    public ULong getLastModifyUserId() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>foundation_item.item_category.is_deleted</code>.
     */
    public void setIsDeleted(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>foundation_item.item_category.is_deleted</code>.
     */
    public ULong getIsDeleted() {
        return (ULong) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<ULong, ULong, LocalDateTime, ULong, LocalDateTime, ULong, ULong> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<ULong, ULong, LocalDateTime, ULong, LocalDateTime, ULong, ULong> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return ItemCategory.ITEM_CATEGORY.ITEM_CATEGORY_ID;
    }

    @Override
    public Field<ULong> field2() {
        return ItemCategory.ITEM_CATEGORY.STORE_ID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return ItemCategory.ITEM_CATEGORY.CREATE_TIME;
    }

    @Override
    public Field<ULong> field4() {
        return ItemCategory.ITEM_CATEGORY.CREATE_USER_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ItemCategory.ITEM_CATEGORY.LAST_MODIFY_TIME;
    }

    @Override
    public Field<ULong> field6() {
        return ItemCategory.ITEM_CATEGORY.LAST_MODIFY_USER_ID;
    }

    @Override
    public Field<ULong> field7() {
        return ItemCategory.ITEM_CATEGORY.IS_DELETED;
    }

    @Override
    public ULong component1() {
        return getItemCategoryId();
    }

    @Override
    public ULong component2() {
        return getStoreId();
    }

    @Override
    public LocalDateTime component3() {
        return getCreateTime();
    }

    @Override
    public ULong component4() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime component5() {
        return getLastModifyTime();
    }

    @Override
    public ULong component6() {
        return getLastModifyUserId();
    }

    @Override
    public ULong component7() {
        return getIsDeleted();
    }

    @Override
    public ULong value1() {
        return getItemCategoryId();
    }

    @Override
    public ULong value2() {
        return getStoreId();
    }

    @Override
    public LocalDateTime value3() {
        return getCreateTime();
    }

    @Override
    public ULong value4() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime value5() {
        return getLastModifyTime();
    }

    @Override
    public ULong value6() {
        return getLastModifyUserId();
    }

    @Override
    public ULong value7() {
        return getIsDeleted();
    }

    @Override
    public ItemCategoryRecord value1(ULong value) {
        setItemCategoryId(value);
        return this;
    }

    @Override
    public ItemCategoryRecord value2(ULong value) {
        setStoreId(value);
        return this;
    }

    @Override
    public ItemCategoryRecord value3(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public ItemCategoryRecord value4(ULong value) {
        setCreateUserId(value);
        return this;
    }

    @Override
    public ItemCategoryRecord value5(LocalDateTime value) {
        setLastModifyTime(value);
        return this;
    }

    @Override
    public ItemCategoryRecord value6(ULong value) {
        setLastModifyUserId(value);
        return this;
    }

    @Override
    public ItemCategoryRecord value7(ULong value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public ItemCategoryRecord values(ULong value1, ULong value2, LocalDateTime value3, ULong value4, LocalDateTime value5, ULong value6, ULong value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemCategoryRecord
     */
    public ItemCategoryRecord() {
        super(ItemCategory.ITEM_CATEGORY);
    }

    /**
     * Create a detached, initialised ItemCategoryRecord
     */
    public ItemCategoryRecord(ULong itemCategoryId, ULong storeId, LocalDateTime createTime, ULong createUserId, LocalDateTime lastModifyTime, ULong lastModifyUserId, ULong isDeleted) {
        super(ItemCategory.ITEM_CATEGORY);

        set(0, itemCategoryId);
        set(1, storeId);
        set(2, createTime);
        set(3, createUserId);
        set(4, lastModifyTime);
        set(5, lastModifyUserId);
        set(6, isDeleted);
    }
}
