/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.notification.impl.jooq.generation.tables.records;


import com.wuda.foundation.notification.impl.jooq.generation.tables.NotificationDefinitionCore;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * 用于定义通知。这个就好像是Java中的Class，实例（Object）通过Class生成；同样的，我们先定义通知的内容，发送方式，使用的模板，接收人等等信息，然后根据定义产生具体的通知。。表中的每条记录都好像Java中定义的一个Class一样。
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationDefinitionCoreRecord extends UpdatableRecordImpl<NotificationDefinitionCoreRecord> implements Record9<ULong, ULong, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> {

    private static final long serialVersionUID = -11306339;

    /**
     * Setter for <code>foundation_notification.notification_definition_core.notification_difinition_core_id</code>.
     */
    public void setNotificationDifinitionCoreId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>foundation_notification.notification_definition_core.notification_difinition_core_id</code>.
     */
    public ULong getNotificationDifinitionCoreId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>foundation_notification.notification_definition_core.notification_definition_id</code>.
     */
    public void setNotificationDefinitionId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>foundation_notification.notification_definition_core.notification_definition_id</code>.
     */
    public ULong getNotificationDefinitionId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>foundation_notification.notification_definition_core.name</code>. 该定义本身的名称，就好像Java语言中定义一个Class，要给这个Class命名
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>foundation_notification.notification_definition_core.name</code>. 该定义本身的名称，就好像Java语言中定义一个Class，要给这个Class命名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>foundation_notification.notification_definition_core.description</code>. 对于该定义的描述
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>foundation_notification.notification_definition_core.description</code>. 对于该定义的描述
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>foundation_notification.notification_definition_core.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>foundation_notification.notification_definition_core.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>foundation_notification.notification_definition_core.create_user_id</code>.
     */
    public void setCreateUserId(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>foundation_notification.notification_definition_core.create_user_id</code>.
     */
    public ULong getCreateUserId() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>foundation_notification.notification_definition_core.last_modify_time</code>.
     */
    public void setLastModifyTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>foundation_notification.notification_definition_core.last_modify_time</code>.
     */
    public LocalDateTime getLastModifyTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>foundation_notification.notification_definition_core.last_modify_user_id</code>.
     */
    public void setLastModifyUserId(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>foundation_notification.notification_definition_core.last_modify_user_id</code>.
     */
    public ULong getLastModifyUserId() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>foundation_notification.notification_definition_core.is_deleted</code>.
     */
    public void setIsDeleted(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>foundation_notification.notification_definition_core.is_deleted</code>.
     */
    public ULong getIsDeleted() {
        return (ULong) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<ULong, ULong, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<ULong, ULong, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return NotificationDefinitionCore.NOTIFICATION_DEFINITION_CORE.NOTIFICATION_DIFINITION_CORE_ID;
    }

    @Override
    public Field<ULong> field2() {
        return NotificationDefinitionCore.NOTIFICATION_DEFINITION_CORE.NOTIFICATION_DEFINITION_ID;
    }

    @Override
    public Field<String> field3() {
        return NotificationDefinitionCore.NOTIFICATION_DEFINITION_CORE.NAME;
    }

    @Override
    public Field<String> field4() {
        return NotificationDefinitionCore.NOTIFICATION_DEFINITION_CORE.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return NotificationDefinitionCore.NOTIFICATION_DEFINITION_CORE.CREATE_TIME;
    }

    @Override
    public Field<ULong> field6() {
        return NotificationDefinitionCore.NOTIFICATION_DEFINITION_CORE.CREATE_USER_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return NotificationDefinitionCore.NOTIFICATION_DEFINITION_CORE.LAST_MODIFY_TIME;
    }

    @Override
    public Field<ULong> field8() {
        return NotificationDefinitionCore.NOTIFICATION_DEFINITION_CORE.LAST_MODIFY_USER_ID;
    }

    @Override
    public Field<ULong> field9() {
        return NotificationDefinitionCore.NOTIFICATION_DEFINITION_CORE.IS_DELETED;
    }

    @Override
    public ULong component1() {
        return getNotificationDifinitionCoreId();
    }

    @Override
    public ULong component2() {
        return getNotificationDefinitionId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public ULong component6() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime component7() {
        return getLastModifyTime();
    }

    @Override
    public ULong component8() {
        return getLastModifyUserId();
    }

    @Override
    public ULong component9() {
        return getIsDeleted();
    }

    @Override
    public ULong value1() {
        return getNotificationDifinitionCoreId();
    }

    @Override
    public ULong value2() {
        return getNotificationDefinitionId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public ULong value6() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime value7() {
        return getLastModifyTime();
    }

    @Override
    public ULong value8() {
        return getLastModifyUserId();
    }

    @Override
    public ULong value9() {
        return getIsDeleted();
    }

    @Override
    public NotificationDefinitionCoreRecord value1(ULong value) {
        setNotificationDifinitionCoreId(value);
        return this;
    }

    @Override
    public NotificationDefinitionCoreRecord value2(ULong value) {
        setNotificationDefinitionId(value);
        return this;
    }

    @Override
    public NotificationDefinitionCoreRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public NotificationDefinitionCoreRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public NotificationDefinitionCoreRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public NotificationDefinitionCoreRecord value6(ULong value) {
        setCreateUserId(value);
        return this;
    }

    @Override
    public NotificationDefinitionCoreRecord value7(LocalDateTime value) {
        setLastModifyTime(value);
        return this;
    }

    @Override
    public NotificationDefinitionCoreRecord value8(ULong value) {
        setLastModifyUserId(value);
        return this;
    }

    @Override
    public NotificationDefinitionCoreRecord value9(ULong value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public NotificationDefinitionCoreRecord values(ULong value1, ULong value2, String value3, String value4, LocalDateTime value5, ULong value6, LocalDateTime value7, ULong value8, ULong value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NotificationDefinitionCoreRecord
     */
    public NotificationDefinitionCoreRecord() {
        super(NotificationDefinitionCore.NOTIFICATION_DEFINITION_CORE);
    }

    /**
     * Create a detached, initialised NotificationDefinitionCoreRecord
     */
    public NotificationDefinitionCoreRecord(ULong notificationDifinitionCoreId, ULong notificationDefinitionId, String name, String description, LocalDateTime createTime, ULong createUserId, LocalDateTime lastModifyTime, ULong lastModifyUserId, ULong isDeleted) {
        super(NotificationDefinitionCore.NOTIFICATION_DEFINITION_CORE);

        set(0, notificationDifinitionCoreId);
        set(1, notificationDefinitionId);
        set(2, name);
        set(3, description);
        set(4, createTime);
        set(5, createUserId);
        set(6, lastModifyTime);
        set(7, lastModifyUserId);
        set(8, isDeleted);
    }
}
