/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.jooq.code.generation.user.tables.records;


import com.wuda.foundation.jooq.code.generation.user.tables.UserCredential;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * 比如password，public key等都是credential
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserCredentialRecord extends UpdatableRecordImpl<UserCredentialRecord> implements Record10<ULong, ULong, UByte, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> {

    private static final long serialVersionUID = -454225563;

    /**
     * Setter for <code>foundation_user.user_credential.user_credential_id</code>.
     */
    public void setUserCredentialId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>foundation_user.user_credential.user_credential_id</code>.
     */
    public ULong getUserCredentialId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>foundation_user.user_credential.user_id</code>. 用户ID
     */
    public void setUserId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>foundation_user.user_credential.user_id</code>. 用户ID
     */
    public ULong getUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>foundation_user.user_credential.type</code>. credential type，比如password、public key
     */
    public void setType(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>foundation_user.user_credential.type</code>. credential type，比如password、public key
     */
    public UByte getType() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>foundation_user.user_credential.value</code>.
     */
    public void setValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>foundation_user.user_credential.value</code>.
     */
    public String getValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>foundation_user.user_credential.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>foundation_user.user_credential.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>foundation_user.user_credential.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>foundation_user.user_credential.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>foundation_user.user_credential.create_user_id</code>.
     */
    public void setCreateUserId(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>foundation_user.user_credential.create_user_id</code>.
     */
    public ULong getCreateUserId() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>foundation_user.user_credential.last_modify_time</code>.
     */
    public void setLastModifyTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>foundation_user.user_credential.last_modify_time</code>.
     */
    public LocalDateTime getLastModifyTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>foundation_user.user_credential.last_modify_user_id</code>.
     */
    public void setLastModifyUserId(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>foundation_user.user_credential.last_modify_user_id</code>.
     */
    public ULong getLastModifyUserId() {
        return (ULong) get(8);
    }

    /**
     * Setter for <code>foundation_user.user_credential.is_deleted</code>.
     */
    public void setIsDeleted(ULong value) {
        set(9, value);
    }

    /**
     * Getter for <code>foundation_user.user_credential.is_deleted</code>.
     */
    public ULong getIsDeleted() {
        return (ULong) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<ULong, ULong, UByte, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<ULong, ULong, UByte, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return UserCredential.USER_CREDENTIAL.USER_CREDENTIAL_ID;
    }

    @Override
    public Field<ULong> field2() {
        return UserCredential.USER_CREDENTIAL.USER_ID;
    }

    @Override
    public Field<UByte> field3() {
        return UserCredential.USER_CREDENTIAL.TYPE;
    }

    @Override
    public Field<String> field4() {
        return UserCredential.USER_CREDENTIAL.VALUE;
    }

    @Override
    public Field<String> field5() {
        return UserCredential.USER_CREDENTIAL.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return UserCredential.USER_CREDENTIAL.CREATE_TIME;
    }

    @Override
    public Field<ULong> field7() {
        return UserCredential.USER_CREDENTIAL.CREATE_USER_ID;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return UserCredential.USER_CREDENTIAL.LAST_MODIFY_TIME;
    }

    @Override
    public Field<ULong> field9() {
        return UserCredential.USER_CREDENTIAL.LAST_MODIFY_USER_ID;
    }

    @Override
    public Field<ULong> field10() {
        return UserCredential.USER_CREDENTIAL.IS_DELETED;
    }

    @Override
    public ULong component1() {
        return getUserCredentialId();
    }

    @Override
    public ULong component2() {
        return getUserId();
    }

    @Override
    public UByte component3() {
        return getType();
    }

    @Override
    public String component4() {
        return getValue();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateTime();
    }

    @Override
    public ULong component7() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime component8() {
        return getLastModifyTime();
    }

    @Override
    public ULong component9() {
        return getLastModifyUserId();
    }

    @Override
    public ULong component10() {
        return getIsDeleted();
    }

    @Override
    public ULong value1() {
        return getUserCredentialId();
    }

    @Override
    public ULong value2() {
        return getUserId();
    }

    @Override
    public UByte value3() {
        return getType();
    }

    @Override
    public String value4() {
        return getValue();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateTime();
    }

    @Override
    public ULong value7() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime value8() {
        return getLastModifyTime();
    }

    @Override
    public ULong value9() {
        return getLastModifyUserId();
    }

    @Override
    public ULong value10() {
        return getIsDeleted();
    }

    @Override
    public UserCredentialRecord value1(ULong value) {
        setUserCredentialId(value);
        return this;
    }

    @Override
    public UserCredentialRecord value2(ULong value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserCredentialRecord value3(UByte value) {
        setType(value);
        return this;
    }

    @Override
    public UserCredentialRecord value4(String value) {
        setValue(value);
        return this;
    }

    @Override
    public UserCredentialRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public UserCredentialRecord value6(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public UserCredentialRecord value7(ULong value) {
        setCreateUserId(value);
        return this;
    }

    @Override
    public UserCredentialRecord value8(LocalDateTime value) {
        setLastModifyTime(value);
        return this;
    }

    @Override
    public UserCredentialRecord value9(ULong value) {
        setLastModifyUserId(value);
        return this;
    }

    @Override
    public UserCredentialRecord value10(ULong value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public UserCredentialRecord values(ULong value1, ULong value2, UByte value3, String value4, String value5, LocalDateTime value6, ULong value7, LocalDateTime value8, ULong value9, ULong value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserCredentialRecord
     */
    public UserCredentialRecord() {
        super(UserCredential.USER_CREDENTIAL);
    }

    /**
     * Create a detached, initialised UserCredentialRecord
     */
    public UserCredentialRecord(ULong userCredentialId, ULong userId, UByte type, String value, String description, LocalDateTime createTime, ULong createUserId, LocalDateTime lastModifyTime, ULong lastModifyUserId, ULong isDeleted) {
        super(UserCredential.USER_CREDENTIAL);

        set(0, userCredentialId);
        set(1, userId);
        set(2, type);
        set(3, value);
        set(4, description);
        set(5, createTime);
        set(6, createUserId);
        set(7, lastModifyTime);
        set(8, lastModifyUserId);
        set(9, isDeleted);
    }
}
