/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.jooq.code.generation.user.tables.records;


import com.wuda.foundation.jooq.code.generation.user.tables.UserPrincipal;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * 用户的身份标记，比如用户名就是一种principal
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPrincipalRecord extends UpdatableRecordImpl<UserPrincipalRecord> implements Record10<ULong, ULong, UByte, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> {

    private static final long serialVersionUID = 1727089753;

    /**
     * Setter for <code>foundation_user.user_principal.user_pricinpal_id</code>.
     */
    public void setUserPricinpalId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>foundation_user.user_principal.user_pricinpal_id</code>.
     */
    public ULong getUserPricinpalId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>foundation_user.user_principal.user_id</code>.
     */
    public void setUserId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>foundation_user.user_principal.user_id</code>.
     */
    public ULong getUserId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>foundation_user.user_principal.type</code>. principal type，比如该principal是username
     */
    public void setType(UByte value) {
        set(2, value);
    }

    /**
     * Getter for <code>foundation_user.user_principal.type</code>. principal type，比如该principal是username
     */
    public UByte getType() {
        return (UByte) get(2);
    }

    /**
     * Setter for <code>foundation_user.user_principal.name</code>. principal name
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>foundation_user.user_principal.name</code>. principal name
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>foundation_user.user_principal.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>foundation_user.user_principal.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>foundation_user.user_principal.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>foundation_user.user_principal.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>foundation_user.user_principal.create_user_id</code>.
     */
    public void setCreateUserId(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>foundation_user.user_principal.create_user_id</code>.
     */
    public ULong getCreateUserId() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>foundation_user.user_principal.last_modify_time</code>.
     */
    public void setLastModifyTime(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>foundation_user.user_principal.last_modify_time</code>.
     */
    public LocalDateTime getLastModifyTime() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>foundation_user.user_principal.last_modify_user_id</code>.
     */
    public void setLastModifyUserId(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>foundation_user.user_principal.last_modify_user_id</code>.
     */
    public ULong getLastModifyUserId() {
        return (ULong) get(8);
    }

    /**
     * Setter for <code>foundation_user.user_principal.is_deleted</code>.
     */
    public void setIsDeleted(ULong value) {
        set(9, value);
    }

    /**
     * Getter for <code>foundation_user.user_principal.is_deleted</code>.
     */
    public ULong getIsDeleted() {
        return (ULong) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<ULong, ULong, UByte, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<ULong, ULong, UByte, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return UserPrincipal.USER_PRINCIPAL.USER_PRICINPAL_ID;
    }

    @Override
    public Field<ULong> field2() {
        return UserPrincipal.USER_PRINCIPAL.USER_ID;
    }

    @Override
    public Field<UByte> field3() {
        return UserPrincipal.USER_PRINCIPAL.TYPE;
    }

    @Override
    public Field<String> field4() {
        return UserPrincipal.USER_PRINCIPAL.NAME;
    }

    @Override
    public Field<String> field5() {
        return UserPrincipal.USER_PRINCIPAL.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return UserPrincipal.USER_PRINCIPAL.CREATE_TIME;
    }

    @Override
    public Field<ULong> field7() {
        return UserPrincipal.USER_PRINCIPAL.CREATE_USER_ID;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return UserPrincipal.USER_PRINCIPAL.LAST_MODIFY_TIME;
    }

    @Override
    public Field<ULong> field9() {
        return UserPrincipal.USER_PRINCIPAL.LAST_MODIFY_USER_ID;
    }

    @Override
    public Field<ULong> field10() {
        return UserPrincipal.USER_PRINCIPAL.IS_DELETED;
    }

    @Override
    public ULong component1() {
        return getUserPricinpalId();
    }

    @Override
    public ULong component2() {
        return getUserId();
    }

    @Override
    public UByte component3() {
        return getType();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateTime();
    }

    @Override
    public ULong component7() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime component8() {
        return getLastModifyTime();
    }

    @Override
    public ULong component9() {
        return getLastModifyUserId();
    }

    @Override
    public ULong component10() {
        return getIsDeleted();
    }

    @Override
    public ULong value1() {
        return getUserPricinpalId();
    }

    @Override
    public ULong value2() {
        return getUserId();
    }

    @Override
    public UByte value3() {
        return getType();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateTime();
    }

    @Override
    public ULong value7() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime value8() {
        return getLastModifyTime();
    }

    @Override
    public ULong value9() {
        return getLastModifyUserId();
    }

    @Override
    public ULong value10() {
        return getIsDeleted();
    }

    @Override
    public UserPrincipalRecord value1(ULong value) {
        setUserPricinpalId(value);
        return this;
    }

    @Override
    public UserPrincipalRecord value2(ULong value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserPrincipalRecord value3(UByte value) {
        setType(value);
        return this;
    }

    @Override
    public UserPrincipalRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserPrincipalRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public UserPrincipalRecord value6(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public UserPrincipalRecord value7(ULong value) {
        setCreateUserId(value);
        return this;
    }

    @Override
    public UserPrincipalRecord value8(LocalDateTime value) {
        setLastModifyTime(value);
        return this;
    }

    @Override
    public UserPrincipalRecord value9(ULong value) {
        setLastModifyUserId(value);
        return this;
    }

    @Override
    public UserPrincipalRecord value10(ULong value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public UserPrincipalRecord values(ULong value1, ULong value2, UByte value3, String value4, String value5, LocalDateTime value6, ULong value7, LocalDateTime value8, ULong value9, ULong value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserPrincipalRecord
     */
    public UserPrincipalRecord() {
        super(UserPrincipal.USER_PRINCIPAL);
    }

    /**
     * Create a detached, initialised UserPrincipalRecord
     */
    public UserPrincipalRecord(ULong userPricinpalId, ULong userId, UByte type, String name, String description, LocalDateTime createTime, ULong createUserId, LocalDateTime lastModifyTime, ULong lastModifyUserId, ULong isDeleted) {
        super(UserPrincipal.USER_PRINCIPAL);

        set(0, userPricinpalId);
        set(1, userId);
        set(2, type);
        set(3, name);
        set(4, description);
        set(5, createTime);
        set(6, createUserId);
        set(7, lastModifyTime);
        set(8, lastModifyUserId);
        set(9, isDeleted);
    }
}
