/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.user.impl.jooq.generation.tables.records;


import com.wuda.foundation.user.impl.jooq.generation.tables.Role;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * 角色。role本身就是一类用户的统称，有category的意味，因此没有role_category这样的表设计。如果有层级关系，比如一级管理员，二级管理员，并且它们之间又有联系，那么可以考虑在role表中增加parent_id这样的字段表示层级关系。
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> implements Record9<ULong, ULong, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> {

    private static final long serialVersionUID = 514197320;

    /**
     * Setter for <code>user.role.role_id</code>.
     */
    public void setRoleId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>user.role.role_id</code>.
     */
    public ULong getRoleId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>user.role.parent_id</code>. 父级
     */
    public void setParentId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>user.role.parent_id</code>. 父级
     */
    public ULong getParentId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>user.role.name</code>. 角色名称，比如：管理员
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user.role.name</code>. 角色名称，比如：管理员
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user.role.description</code>. 描述
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user.role.description</code>. 描述
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user.role.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>user.role.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>user.role.create_user_id</code>.
     */
    public void setCreateUserId(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>user.role.create_user_id</code>.
     */
    public ULong getCreateUserId() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>user.role.last_modify_time</code>.
     */
    public void setLastModifyTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>user.role.last_modify_time</code>.
     */
    public LocalDateTime getLastModifyTime() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>user.role.last_modify_user_id</code>.
     */
    public void setLastModifyUserId(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>user.role.last_modify_user_id</code>.
     */
    public ULong getLastModifyUserId() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>user.role.is_deleted</code>.
     */
    public void setIsDeleted(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>user.role.is_deleted</code>.
     */
    public ULong getIsDeleted() {
        return (ULong) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<ULong, ULong, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<ULong, ULong, String, String, LocalDateTime, ULong, LocalDateTime, ULong, ULong> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return Role.ROLE.ROLE_ID;
    }

    @Override
    public Field<ULong> field2() {
        return Role.ROLE.PARENT_ID;
    }

    @Override
    public Field<String> field3() {
        return Role.ROLE.NAME;
    }

    @Override
    public Field<String> field4() {
        return Role.ROLE.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Role.ROLE.CREATE_TIME;
    }

    @Override
    public Field<ULong> field6() {
        return Role.ROLE.CREATE_USER_ID;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return Role.ROLE.LAST_MODIFY_TIME;
    }

    @Override
    public Field<ULong> field8() {
        return Role.ROLE.LAST_MODIFY_USER_ID;
    }

    @Override
    public Field<ULong> field9() {
        return Role.ROLE.IS_DELETED;
    }

    @Override
    public ULong component1() {
        return getRoleId();
    }

    @Override
    public ULong component2() {
        return getParentId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public ULong component6() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime component7() {
        return getLastModifyTime();
    }

    @Override
    public ULong component8() {
        return getLastModifyUserId();
    }

    @Override
    public ULong component9() {
        return getIsDeleted();
    }

    @Override
    public ULong value1() {
        return getRoleId();
    }

    @Override
    public ULong value2() {
        return getParentId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public ULong value6() {
        return getCreateUserId();
    }

    @Override
    public LocalDateTime value7() {
        return getLastModifyTime();
    }

    @Override
    public ULong value8() {
        return getLastModifyUserId();
    }

    @Override
    public ULong value9() {
        return getIsDeleted();
    }

    @Override
    public RoleRecord value1(ULong value) {
        setRoleId(value);
        return this;
    }

    @Override
    public RoleRecord value2(ULong value) {
        setParentId(value);
        return this;
    }

    @Override
    public RoleRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public RoleRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public RoleRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public RoleRecord value6(ULong value) {
        setCreateUserId(value);
        return this;
    }

    @Override
    public RoleRecord value7(LocalDateTime value) {
        setLastModifyTime(value);
        return this;
    }

    @Override
    public RoleRecord value8(ULong value) {
        setLastModifyUserId(value);
        return this;
    }

    @Override
    public RoleRecord value9(ULong value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public RoleRecord values(ULong value1, ULong value2, String value3, String value4, LocalDateTime value5, ULong value6, LocalDateTime value7, ULong value8, ULong value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleRecord
     */
    public RoleRecord() {
        super(Role.ROLE);
    }

    /**
     * Create a detached, initialised RoleRecord
     */
    public RoleRecord(ULong roleId, ULong parentId, String name, String description, LocalDateTime createTime, ULong createUserId, LocalDateTime lastModifyTime, ULong lastModifyUserId, ULong isDeleted) {
        super(Role.ROLE);

        set(0, roleId);
        set(1, parentId);
        set(2, name);
        set(3, description);
        set(4, createTime);
        set(5, createUserId);
        set(6, lastModifyTime);
        set(7, lastModifyUserId);
        set(8, isDeleted);
    }
}
