/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.notification.impl.jooq.generation.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.ULong;


/**
 * 代表一条实际已经发送的通知。通知模块的设计，不局限于发给用户，或者从用户发出来，任何实体都可以发送和接收，比如service A可以发送给service 
 * B，因此会有receiver type和sender type的设计。同样的内容，可以通过多种方式发送，比如通过邮件，短信发送同样的内容，因此发送方式不放到这个表中，这样的好处是不同的发送方式可以指向（共享）同一个通知。
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationInstanceContent implements Serializable {

    private static final long serialVersionUID = -462897831;

    private ULong         notificationInstanceContentId;
    private ULong         notificationDefinitionId;
    private ULong         notificationDefinitionSendMethodId;
    private ULong         notificationDefinitionContentId;
    private ULong         notificationCategoryId;
    private String        title;
    private String        body;
    private LocalDateTime createTime;
    private ULong         createUserId;
    private LocalDateTime lastModifyTime;
    private ULong         lastModifyUserId;
    private ULong         isDeleted;

    public NotificationInstanceContent() {}

    public NotificationInstanceContent(NotificationInstanceContent value) {
        this.notificationInstanceContentId = value.notificationInstanceContentId;
        this.notificationDefinitionId = value.notificationDefinitionId;
        this.notificationDefinitionSendMethodId = value.notificationDefinitionSendMethodId;
        this.notificationDefinitionContentId = value.notificationDefinitionContentId;
        this.notificationCategoryId = value.notificationCategoryId;
        this.title = value.title;
        this.body = value.body;
        this.createTime = value.createTime;
        this.createUserId = value.createUserId;
        this.lastModifyTime = value.lastModifyTime;
        this.lastModifyUserId = value.lastModifyUserId;
        this.isDeleted = value.isDeleted;
    }

    public NotificationInstanceContent(
        ULong         notificationInstanceContentId,
        ULong         notificationDefinitionId,
        ULong         notificationDefinitionSendMethodId,
        ULong         notificationDefinitionContentId,
        ULong         notificationCategoryId,
        String        title,
        String        body,
        LocalDateTime createTime,
        ULong         createUserId,
        LocalDateTime lastModifyTime,
        ULong         lastModifyUserId,
        ULong         isDeleted
    ) {
        this.notificationInstanceContentId = notificationInstanceContentId;
        this.notificationDefinitionId = notificationDefinitionId;
        this.notificationDefinitionSendMethodId = notificationDefinitionSendMethodId;
        this.notificationDefinitionContentId = notificationDefinitionContentId;
        this.notificationCategoryId = notificationCategoryId;
        this.title = title;
        this.body = body;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.lastModifyTime = lastModifyTime;
        this.lastModifyUserId = lastModifyUserId;
        this.isDeleted = isDeleted;
    }

    public ULong getNotificationInstanceContentId() {
        return this.notificationInstanceContentId;
    }

    public void setNotificationInstanceContentId(ULong notificationInstanceContentId) {
        this.notificationInstanceContentId = notificationInstanceContentId;
    }

    public ULong getNotificationDefinitionId() {
        return this.notificationDefinitionId;
    }

    public void setNotificationDefinitionId(ULong notificationDefinitionId) {
        this.notificationDefinitionId = notificationDefinitionId;
    }

    public ULong getNotificationDefinitionSendMethodId() {
        return this.notificationDefinitionSendMethodId;
    }

    public void setNotificationDefinitionSendMethodId(ULong notificationDefinitionSendMethodId) {
        this.notificationDefinitionSendMethodId = notificationDefinitionSendMethodId;
    }

    public ULong getNotificationDefinitionContentId() {
        return this.notificationDefinitionContentId;
    }

    public void setNotificationDefinitionContentId(ULong notificationDefinitionContentId) {
        this.notificationDefinitionContentId = notificationDefinitionContentId;
    }

    public ULong getNotificationCategoryId() {
        return this.notificationCategoryId;
    }

    public void setNotificationCategoryId(ULong notificationCategoryId) {
        this.notificationCategoryId = notificationCategoryId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBody() {
        return this.body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public ULong getCreateUserId() {
        return this.createUserId;
    }

    public void setCreateUserId(ULong createUserId) {
        this.createUserId = createUserId;
    }

    public LocalDateTime getLastModifyTime() {
        return this.lastModifyTime;
    }

    public void setLastModifyTime(LocalDateTime lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    public ULong getLastModifyUserId() {
        return this.lastModifyUserId;
    }

    public void setLastModifyUserId(ULong lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    public ULong getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(ULong isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NotificationInstanceContent (");

        sb.append(notificationInstanceContentId);
        sb.append(", ").append(notificationDefinitionId);
        sb.append(", ").append(notificationDefinitionSendMethodId);
        sb.append(", ").append(notificationDefinitionContentId);
        sb.append(", ").append(notificationCategoryId);
        sb.append(", ").append(title);
        sb.append(", ").append(body);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createUserId);
        sb.append(", ").append(lastModifyTime);
        sb.append(", ").append(lastModifyUserId);
        sb.append(", ").append(isDeleted);

        sb.append(")");
        return sb.toString();
    }
}
