/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.notification.impl.jooq.generation.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * 定义通知的观察者，用于接收或者查看通知
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationDefinitionObserver implements Serializable {

    private static final long serialVersionUID = 2042495658;

    private ULong         notificationDefinitionObserverId;
    private ULong         notificationDefinitionId;
    private ULong         notificationDefinitionSendMethodId;
    private UByte         observerType;
    private ULong         observerIdentifier;
    private LocalDateTime createTime;
    private ULong         createUserId;
    private LocalDateTime lastModifyTime;
    private ULong         lastModifyUserId;
    private ULong         isDeleted;

    public NotificationDefinitionObserver() {}

    public NotificationDefinitionObserver(NotificationDefinitionObserver value) {
        this.notificationDefinitionObserverId = value.notificationDefinitionObserverId;
        this.notificationDefinitionId = value.notificationDefinitionId;
        this.notificationDefinitionSendMethodId = value.notificationDefinitionSendMethodId;
        this.observerType = value.observerType;
        this.observerIdentifier = value.observerIdentifier;
        this.createTime = value.createTime;
        this.createUserId = value.createUserId;
        this.lastModifyTime = value.lastModifyTime;
        this.lastModifyUserId = value.lastModifyUserId;
        this.isDeleted = value.isDeleted;
    }

    public NotificationDefinitionObserver(
        ULong         notificationDefinitionObserverId,
        ULong         notificationDefinitionId,
        ULong         notificationDefinitionSendMethodId,
        UByte         observerType,
        ULong         observerIdentifier,
        LocalDateTime createTime,
        ULong         createUserId,
        LocalDateTime lastModifyTime,
        ULong         lastModifyUserId,
        ULong         isDeleted
    ) {
        this.notificationDefinitionObserverId = notificationDefinitionObserverId;
        this.notificationDefinitionId = notificationDefinitionId;
        this.notificationDefinitionSendMethodId = notificationDefinitionSendMethodId;
        this.observerType = observerType;
        this.observerIdentifier = observerIdentifier;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.lastModifyTime = lastModifyTime;
        this.lastModifyUserId = lastModifyUserId;
        this.isDeleted = isDeleted;
    }

    public ULong getNotificationDefinitionObserverId() {
        return this.notificationDefinitionObserverId;
    }

    public void setNotificationDefinitionObserverId(ULong notificationDefinitionObserverId) {
        this.notificationDefinitionObserverId = notificationDefinitionObserverId;
    }

    public ULong getNotificationDefinitionId() {
        return this.notificationDefinitionId;
    }

    public void setNotificationDefinitionId(ULong notificationDefinitionId) {
        this.notificationDefinitionId = notificationDefinitionId;
    }

    public ULong getNotificationDefinitionSendMethodId() {
        return this.notificationDefinitionSendMethodId;
    }

    public void setNotificationDefinitionSendMethodId(ULong notificationDefinitionSendMethodId) {
        this.notificationDefinitionSendMethodId = notificationDefinitionSendMethodId;
    }

    public UByte getObserverType() {
        return this.observerType;
    }

    public void setObserverType(UByte observerType) {
        this.observerType = observerType;
    }

    public ULong getObserverIdentifier() {
        return this.observerIdentifier;
    }

    public void setObserverIdentifier(ULong observerIdentifier) {
        this.observerIdentifier = observerIdentifier;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public ULong getCreateUserId() {
        return this.createUserId;
    }

    public void setCreateUserId(ULong createUserId) {
        this.createUserId = createUserId;
    }

    public LocalDateTime getLastModifyTime() {
        return this.lastModifyTime;
    }

    public void setLastModifyTime(LocalDateTime lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    public ULong getLastModifyUserId() {
        return this.lastModifyUserId;
    }

    public void setLastModifyUserId(ULong lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    public ULong getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(ULong isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NotificationDefinitionObserver (");

        sb.append(notificationDefinitionObserverId);
        sb.append(", ").append(notificationDefinitionId);
        sb.append(", ").append(notificationDefinitionSendMethodId);
        sb.append(", ").append(observerType);
        sb.append(", ").append(observerIdentifier);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createUserId);
        sb.append(", ").append(lastModifyTime);
        sb.append(", ").append(lastModifyUserId);
        sb.append(", ").append(isDeleted);

        sb.append(")");
        return sb.toString();
    }
}
