/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.core.store.impl.jooq.generation;


import com.wuda.foundation.core.store.impl.jooq.generation.tables.StoreCore;
import com.wuda.foundation.core.store.impl.jooq.generation.tables.StoreGeneral;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FoundationStore extends SchemaImpl {

    private static final long serialVersionUID = -1930390619;

    /**
     * The reference instance of <code>foundation_store</code>
     */
    public static final FoundationStore FOUNDATION_STORE = new FoundationStore();

    /**
     * 店铺信息
     */
    public final StoreCore STORE_CORE = StoreCore.STORE_CORE;

    /**
     * 店铺基本信息
     */
    public final StoreGeneral STORE_GENERAL = StoreGeneral.STORE_GENERAL;

    /**
     * No further instances allowed
     */
    private FoundationStore() {
        super("foundation_store", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            StoreCore.STORE_CORE,
            StoreGeneral.STORE_GENERAL);
    }
}
