/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.jooq.code.generation.commons.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * 物品分类
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MenuItemCategory implements Serializable {

    private static final long serialVersionUID = 922885956;

    private ULong         menuItemCategoryId;
    private ULong         menuId;
    private ULong         parentMenuItemCategoryId;
    private ULong         rootMenuItemCategoryId;
    private UByte         depth;
    private String        name;
    private String        description;
    private LocalDateTime createTime;
    private ULong         createUserId;
    private LocalDateTime lastModifyTime;
    private ULong         lastModifyUserId;
    private ULong         isDeleted;

    public MenuItemCategory() {}

    public MenuItemCategory(MenuItemCategory value) {
        this.menuItemCategoryId = value.menuItemCategoryId;
        this.menuId = value.menuId;
        this.parentMenuItemCategoryId = value.parentMenuItemCategoryId;
        this.rootMenuItemCategoryId = value.rootMenuItemCategoryId;
        this.depth = value.depth;
        this.name = value.name;
        this.description = value.description;
        this.createTime = value.createTime;
        this.createUserId = value.createUserId;
        this.lastModifyTime = value.lastModifyTime;
        this.lastModifyUserId = value.lastModifyUserId;
        this.isDeleted = value.isDeleted;
    }

    public MenuItemCategory(
        ULong         menuItemCategoryId,
        ULong         menuId,
        ULong         parentMenuItemCategoryId,
        ULong         rootMenuItemCategoryId,
        UByte         depth,
        String        name,
        String        description,
        LocalDateTime createTime,
        ULong         createUserId,
        LocalDateTime lastModifyTime,
        ULong         lastModifyUserId,
        ULong         isDeleted
    ) {
        this.menuItemCategoryId = menuItemCategoryId;
        this.menuId = menuId;
        this.parentMenuItemCategoryId = parentMenuItemCategoryId;
        this.rootMenuItemCategoryId = rootMenuItemCategoryId;
        this.depth = depth;
        this.name = name;
        this.description = description;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.lastModifyTime = lastModifyTime;
        this.lastModifyUserId = lastModifyUserId;
        this.isDeleted = isDeleted;
    }

    public ULong getMenuItemCategoryId() {
        return this.menuItemCategoryId;
    }

    public void setMenuItemCategoryId(ULong menuItemCategoryId) {
        this.menuItemCategoryId = menuItemCategoryId;
    }

    public ULong getMenuId() {
        return this.menuId;
    }

    public void setMenuId(ULong menuId) {
        this.menuId = menuId;
    }

    public ULong getParentMenuItemCategoryId() {
        return this.parentMenuItemCategoryId;
    }

    public void setParentMenuItemCategoryId(ULong parentMenuItemCategoryId) {
        this.parentMenuItemCategoryId = parentMenuItemCategoryId;
    }

    public ULong getRootMenuItemCategoryId() {
        return this.rootMenuItemCategoryId;
    }

    public void setRootMenuItemCategoryId(ULong rootMenuItemCategoryId) {
        this.rootMenuItemCategoryId = rootMenuItemCategoryId;
    }

    public UByte getDepth() {
        return this.depth;
    }

    public void setDepth(UByte depth) {
        this.depth = depth;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public ULong getCreateUserId() {
        return this.createUserId;
    }

    public void setCreateUserId(ULong createUserId) {
        this.createUserId = createUserId;
    }

    public LocalDateTime getLastModifyTime() {
        return this.lastModifyTime;
    }

    public void setLastModifyTime(LocalDateTime lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    public ULong getLastModifyUserId() {
        return this.lastModifyUserId;
    }

    public void setLastModifyUserId(ULong lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    public ULong getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(ULong isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MenuItemCategory (");

        sb.append(menuItemCategoryId);
        sb.append(", ").append(menuId);
        sb.append(", ").append(parentMenuItemCategoryId);
        sb.append(", ").append(rootMenuItemCategoryId);
        sb.append(", ").append(depth);
        sb.append(", ").append(name);
        sb.append(", ").append(description);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createUserId);
        sb.append(", ").append(lastModifyTime);
        sb.append(", ").append(lastModifyUserId);
        sb.append(", ").append(isDeleted);

        sb.append(")");
        return sb.toString();
    }
}
