/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos;


import org.jooq.types.UByte;
import org.jooq.types.ULong;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 通知的追踪信息，比如是否被接收者阅读
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationInstanceTrace implements Serializable {

    private static final long serialVersionUID = 1294282238;

    private ULong         notificationInstanceTraceId;
    private ULong         notificationInstanceContentId;
    private UByte         observerType;
    private ULong         observerIdentifier;
    private Boolean       read;
    private LocalDateTime readTime;
    private LocalDateTime createTime;
    private ULong         createUserId;
    private LocalDateTime lastModifyTime;
    private Long          lastModifyUserId;
    private ULong         isDeleted;

    public NotificationInstanceTrace() {}

    public NotificationInstanceTrace(NotificationInstanceTrace value) {
        this.notificationInstanceTraceId = value.notificationInstanceTraceId;
        this.notificationInstanceContentId = value.notificationInstanceContentId;
        this.observerType = value.observerType;
        this.observerIdentifier = value.observerIdentifier;
        this.read = value.read;
        this.readTime = value.readTime;
        this.createTime = value.createTime;
        this.createUserId = value.createUserId;
        this.lastModifyTime = value.lastModifyTime;
        this.lastModifyUserId = value.lastModifyUserId;
        this.isDeleted = value.isDeleted;
    }

    public NotificationInstanceTrace(
        ULong         notificationInstanceTraceId,
        ULong         notificationInstanceContentId,
        UByte         observerType,
        ULong         observerIdentifier,
        Boolean       read,
        LocalDateTime readTime,
        LocalDateTime createTime,
        ULong         createUserId,
        LocalDateTime lastModifyTime,
        Long          lastModifyUserId,
        ULong         isDeleted
    ) {
        this.notificationInstanceTraceId = notificationInstanceTraceId;
        this.notificationInstanceContentId = notificationInstanceContentId;
        this.observerType = observerType;
        this.observerIdentifier = observerIdentifier;
        this.read = read;
        this.readTime = readTime;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.lastModifyTime = lastModifyTime;
        this.lastModifyUserId = lastModifyUserId;
        this.isDeleted = isDeleted;
    }

    public ULong getNotificationInstanceTraceId() {
        return this.notificationInstanceTraceId;
    }

    public void setNotificationInstanceTraceId(ULong notificationInstanceTraceId) {
        this.notificationInstanceTraceId = notificationInstanceTraceId;
    }

    public ULong getNotificationInstanceContentId() {
        return this.notificationInstanceContentId;
    }

    public void setNotificationInstanceContentId(ULong notificationInstanceContentId) {
        this.notificationInstanceContentId = notificationInstanceContentId;
    }

    public UByte getObserverType() {
        return this.observerType;
    }

    public void setObserverType(UByte observerType) {
        this.observerType = observerType;
    }

    public ULong getObserverIdentifier() {
        return this.observerIdentifier;
    }

    public void setObserverIdentifier(ULong observerIdentifier) {
        this.observerIdentifier = observerIdentifier;
    }

    public Boolean getRead() {
        return this.read;
    }

    public void setRead(Boolean read) {
        this.read = read;
    }

    public LocalDateTime getReadTime() {
        return this.readTime;
    }

    public void setReadTime(LocalDateTime readTime) {
        this.readTime = readTime;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public ULong getCreateUserId() {
        return this.createUserId;
    }

    public void setCreateUserId(ULong createUserId) {
        this.createUserId = createUserId;
    }

    public LocalDateTime getLastModifyTime() {
        return this.lastModifyTime;
    }

    public void setLastModifyTime(LocalDateTime lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    public Long getLastModifyUserId() {
        return this.lastModifyUserId;
    }

    public void setLastModifyUserId(Long lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    public ULong getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(ULong isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("NotificationInstanceTrace (");

        sb.append(notificationInstanceTraceId);
        sb.append(", ").append(notificationInstanceContentId);
        sb.append(", ").append(observerType);
        sb.append(", ").append(observerIdentifier);
        sb.append(", ").append(read);
        sb.append(", ").append(readTime);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createUserId);
        sb.append(", ").append(lastModifyTime);
        sb.append(", ").append(lastModifyUserId);
        sb.append(", ").append(isDeleted);

        sb.append(")");
        return sb.toString();
    }
}
