/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.item.impl.jooq.generation.tables;


import com.wuda.foundation.item.impl.jooq.generation.FoundationItem;
import com.wuda.foundation.item.impl.jooq.generation.Indexes;
import com.wuda.foundation.item.impl.jooq.generation.Keys;
import com.wuda.foundation.item.impl.jooq.generation.tables.records.ItemCategoryRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;


/**
 * 物品分类
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemCategory extends TableImpl<ItemCategoryRecord> {

    private static final long serialVersionUID = 81941343;

    /**
     * The reference instance of <code>foundation_item.item_category</code>
     */
    public static final ItemCategory ITEM_CATEGORY = new ItemCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ItemCategoryRecord> getRecordType() {
        return ItemCategoryRecord.class;
    }

    /**
     * The column <code>foundation_item.item_category.item_category_id</code>. 一定和【tree_node.tree_node_id】相等，因为实际表示树形结构的数据在tree_node表中，这里只是对tree_node的引用。tree_node表负责树形结构的维护，这里维护树形结构以外的内容，比如store_id字段用于维护归属。
     */
    public final TableField<ItemCategoryRecord, ULong> ITEM_CATEGORY_ID = createField(DSL.name("item_category_id"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).identity(true), this, "一定和【tree_node.tree_node_id】相等，因为实际表示树形结构的数据在tree_node表中，这里只是对tree_node的引用。tree_node表负责树形结构的维护，这里维护树形结构以外的内容，比如store_id字段用于维护归属。");

    /**
     * The column <code>foundation_item.item_category.store_id</code>. 所属店铺ID
     */
    public final TableField<ItemCategoryRecord, ULong> STORE_ID = createField(DSL.name("store_id"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "所属店铺ID");

    /**
     * The column <code>foundation_item.item_category.create_time</code>.
     */
    public final TableField<ItemCategoryRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>foundation_item.item_category.create_user_id</code>.
     */
    public final TableField<ItemCategoryRecord, ULong> CREATE_USER_ID = createField(DSL.name("create_user_id"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>foundation_item.item_category.last_modify_time</code>.
     */
    public final TableField<ItemCategoryRecord, LocalDateTime> LAST_MODIFY_TIME = createField(DSL.name("last_modify_time"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>foundation_item.item_category.last_modify_user_id</code>.
     */
    public final TableField<ItemCategoryRecord, ULong> LAST_MODIFY_USER_ID = createField(DSL.name("last_modify_user_id"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>foundation_item.item_category.is_deleted</code>.
     */
    public final TableField<ItemCategoryRecord, ULong> IS_DELETED = createField(DSL.name("is_deleted"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINTUNSIGNED)), this, "");

    /**
     * Create a <code>foundation_item.item_category</code> table reference
     */
    public ItemCategory() {
        this(DSL.name("item_category"), null);
    }

    /**
     * Create an aliased <code>foundation_item.item_category</code> table reference
     */
    public ItemCategory(String alias) {
        this(DSL.name(alias), ITEM_CATEGORY);
    }

    /**
     * Create an aliased <code>foundation_item.item_category</code> table reference
     */
    public ItemCategory(Name alias) {
        this(alias, ITEM_CATEGORY);
    }

    private ItemCategory(Name alias, Table<ItemCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private ItemCategory(Name alias, Table<ItemCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("物品分类"), TableOptions.table());
    }

    public <O extends Record> ItemCategory(Table<O> child, ForeignKey<O, ItemCategoryRecord> key) {
        super(child, key, ITEM_CATEGORY);
    }

    @Override
    public Schema getSchema() {
        return FoundationItem.FOUNDATION_ITEM;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ITEM_CATEGORY_FK_STORE_ID);
    }

    @Override
    public Identity<ItemCategoryRecord, ULong> getIdentity() {
        return Keys.IDENTITY_ITEM_CATEGORY;
    }

    @Override
    public UniqueKey<ItemCategoryRecord> getPrimaryKey() {
        return Keys.KEY_ITEM_CATEGORY_PRIMARY;
    }

    @Override
    public List<UniqueKey<ItemCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<ItemCategoryRecord>>asList(Keys.KEY_ITEM_CATEGORY_PRIMARY);
    }

    @Override
    public ItemCategory as(String alias) {
        return new ItemCategory(DSL.name(alias), this);
    }

    @Override
    public ItemCategory as(Name alias) {
        return new ItemCategory(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemCategory rename(String name) {
        return new ItemCategory(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ItemCategory rename(Name name) {
        return new ItemCategory(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<ULong, ULong, LocalDateTime, ULong, LocalDateTime, ULong, ULong> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
