/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.security.impl.jooq.generation.tables.records;


import com.wuda.foundation.security.impl.jooq.generation.tables.SubjectPermission;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * subject可以代表用户，也可以代表想要访问其他资源的应用，suibject与permission的关联关系表。比如我们可以说user 【IS 
 * A】 subject
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectPermissionRecord extends UpdatableRecordImpl<SubjectPermissionRecord> implements Record8<ULong, UByte, ULong, ULong, ULong, LocalDateTime, ULong, ULong> {

    private static final long serialVersionUID = -49076353;

    /**
     * Setter for <code>foundation_security.subject_permission.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>foundation_security.subject_permission.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>foundation_security.subject_permission.subject_type</code>. subject的类型，比如subject代表用户
     */
    public void setSubjectType(UByte value) {
        set(1, value);
    }

    /**
     * Getter for <code>foundation_security.subject_permission.subject_type</code>. subject的类型，比如subject代表用户
     */
    public UByte getSubjectType() {
        return (UByte) get(1);
    }

    /**
     * Setter for <code>foundation_security.subject_permission.subject_identifier</code>. 如果subject type代表用户，那么这个值可能就是用户ID
     */
    public void setSubjectIdentifier(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>foundation_security.subject_permission.subject_identifier</code>. 如果subject type代表用户，那么这个值可能就是用户ID
     */
    public ULong getSubjectIdentifier() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>foundation_security.subject_permission.persission_target_id</code>.
     */
    public void setPersissionTargetId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>foundation_security.subject_permission.persission_target_id</code>.
     */
    public ULong getPersissionTargetId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>foundation_security.subject_permission.permission_action_id</code>. permission action id，如果为0，则表示没有分配action
     */
    public void setPermissionActionId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>foundation_security.subject_permission.permission_action_id</code>. permission action id，如果为0，则表示没有分配action
     */
    public ULong getPermissionActionId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>foundation_security.subject_permission.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>foundation_security.subject_permission.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>foundation_security.subject_permission.create_user_id</code>.
     */
    public void setCreateUserId(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>foundation_security.subject_permission.create_user_id</code>.
     */
    public ULong getCreateUserId() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>foundation_security.subject_permission.is_deleted</code>.
     */
    public void setIsDeleted(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>foundation_security.subject_permission.is_deleted</code>.
     */
    public ULong getIsDeleted() {
        return (ULong) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<ULong, UByte, ULong, ULong, ULong, LocalDateTime, ULong, ULong> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<ULong, UByte, ULong, ULong, ULong, LocalDateTime, ULong, ULong> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return SubjectPermission.SUBJECT_PERMISSION.ID;
    }

    @Override
    public Field<UByte> field2() {
        return SubjectPermission.SUBJECT_PERMISSION.SUBJECT_TYPE;
    }

    @Override
    public Field<ULong> field3() {
        return SubjectPermission.SUBJECT_PERMISSION.SUBJECT_IDENTIFIER;
    }

    @Override
    public Field<ULong> field4() {
        return SubjectPermission.SUBJECT_PERMISSION.PERSISSION_TARGET_ID;
    }

    @Override
    public Field<ULong> field5() {
        return SubjectPermission.SUBJECT_PERMISSION.PERMISSION_ACTION_ID;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SubjectPermission.SUBJECT_PERMISSION.CREATE_TIME;
    }

    @Override
    public Field<ULong> field7() {
        return SubjectPermission.SUBJECT_PERMISSION.CREATE_USER_ID;
    }

    @Override
    public Field<ULong> field8() {
        return SubjectPermission.SUBJECT_PERMISSION.IS_DELETED;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public UByte component2() {
        return getSubjectType();
    }

    @Override
    public ULong component3() {
        return getSubjectIdentifier();
    }

    @Override
    public ULong component4() {
        return getPersissionTargetId();
    }

    @Override
    public ULong component5() {
        return getPermissionActionId();
    }

    @Override
    public LocalDateTime component6() {
        return getCreateTime();
    }

    @Override
    public ULong component7() {
        return getCreateUserId();
    }

    @Override
    public ULong component8() {
        return getIsDeleted();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public UByte value2() {
        return getSubjectType();
    }

    @Override
    public ULong value3() {
        return getSubjectIdentifier();
    }

    @Override
    public ULong value4() {
        return getPersissionTargetId();
    }

    @Override
    public ULong value5() {
        return getPermissionActionId();
    }

    @Override
    public LocalDateTime value6() {
        return getCreateTime();
    }

    @Override
    public ULong value7() {
        return getCreateUserId();
    }

    @Override
    public ULong value8() {
        return getIsDeleted();
    }

    @Override
    public SubjectPermissionRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public SubjectPermissionRecord value2(UByte value) {
        setSubjectType(value);
        return this;
    }

    @Override
    public SubjectPermissionRecord value3(ULong value) {
        setSubjectIdentifier(value);
        return this;
    }

    @Override
    public SubjectPermissionRecord value4(ULong value) {
        setPersissionTargetId(value);
        return this;
    }

    @Override
    public SubjectPermissionRecord value5(ULong value) {
        setPermissionActionId(value);
        return this;
    }

    @Override
    public SubjectPermissionRecord value6(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SubjectPermissionRecord value7(ULong value) {
        setCreateUserId(value);
        return this;
    }

    @Override
    public SubjectPermissionRecord value8(ULong value) {
        setIsDeleted(value);
        return this;
    }

    @Override
    public SubjectPermissionRecord values(ULong value1, UByte value2, ULong value3, ULong value4, ULong value5, LocalDateTime value6, ULong value7, ULong value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SubjectPermissionRecord
     */
    public SubjectPermissionRecord() {
        super(SubjectPermission.SUBJECT_PERMISSION);
    }

    /**
     * Create a detached, initialised SubjectPermissionRecord
     */
    public SubjectPermissionRecord(ULong id, UByte subjectType, ULong subjectIdentifier, ULong persissionTargetId, ULong permissionActionId, LocalDateTime createTime, ULong createUserId, ULong isDeleted) {
        super(SubjectPermission.SUBJECT_PERMISSION);

        set(0, id);
        set(1, subjectType);
        set(2, subjectIdentifier);
        set(3, persissionTargetId);
        set(4, permissionActionId);
        set(5, createTime);
        set(6, createUserId);
        set(7, isDeleted);
    }
}
