/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.store.impl.jooq.generation;


import com.wuda.foundation.store.impl.jooq.generation.tables.Store;
import com.wuda.foundation.store.impl.jooq.generation.tables.StoreGeneral;


/**
 * Convenience access to all tables in store
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 店铺信息
     */
    public static final Store STORE_ = Store.STORE_;

    /**
     * 店铺基本信息
     */
    public static final StoreGeneral STORE_GENERAL = StoreGeneral.STORE_GENERAL;
}
