/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.jooq.code.generation.item;


import com.wuda.foundation.jooq.code.generation.item.tables.ItemBelongsToGroup;
import com.wuda.foundation.jooq.code.generation.item.tables.ItemCategory;
import com.wuda.foundation.jooq.code.generation.item.tables.ItemCore;
import com.wuda.foundation.jooq.code.generation.item.tables.ItemDescription;
import com.wuda.foundation.jooq.code.generation.item.tables.ItemGeneral;
import com.wuda.foundation.jooq.code.generation.item.tables.ItemPrice;
import com.wuda.foundation.jooq.code.generation.item.tables.ItemVariation;
import com.wuda.foundation.jooq.code.generation.item.tables.records.ItemBelongsToGroupRecord;
import com.wuda.foundation.jooq.code.generation.item.tables.records.ItemCategoryRecord;
import com.wuda.foundation.jooq.code.generation.item.tables.records.ItemCoreRecord;
import com.wuda.foundation.jooq.code.generation.item.tables.records.ItemDescriptionRecord;
import com.wuda.foundation.jooq.code.generation.item.tables.records.ItemGeneralRecord;
import com.wuda.foundation.jooq.code.generation.item.tables.records.ItemPriceRecord;
import com.wuda.foundation.jooq.code.generation.item.tables.records.ItemVariationRecord;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;
import org.jooq.types.ULong;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>foundation_item</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ItemBelongsToGroupRecord, ULong> IDENTITY_ITEM_BELONGS_TO_GROUP = Identities0.IDENTITY_ITEM_BELONGS_TO_GROUP;
    public static final Identity<ItemCategoryRecord, ULong> IDENTITY_ITEM_CATEGORY = Identities0.IDENTITY_ITEM_CATEGORY;
    public static final Identity<ItemCoreRecord, ULong> IDENTITY_ITEM_CORE = Identities0.IDENTITY_ITEM_CORE;
    public static final Identity<ItemDescriptionRecord, ULong> IDENTITY_ITEM_DESCRIPTION = Identities0.IDENTITY_ITEM_DESCRIPTION;
    public static final Identity<ItemGeneralRecord, ULong> IDENTITY_ITEM_GENERAL = Identities0.IDENTITY_ITEM_GENERAL;
    public static final Identity<ItemVariationRecord, ULong> IDENTITY_ITEM_VARIATION = Identities0.IDENTITY_ITEM_VARIATION;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ItemBelongsToGroupRecord> KEY_ITEM_BELONGS_TO_GROUP_PRIMARY = UniqueKeys0.KEY_ITEM_BELONGS_TO_GROUP_PRIMARY;
    public static final UniqueKey<ItemCategoryRecord> KEY_ITEM_CATEGORY_PRIMARY = UniqueKeys0.KEY_ITEM_CATEGORY_PRIMARY;
    public static final UniqueKey<ItemCoreRecord> KEY_ITEM_CORE_PRIMARY = UniqueKeys0.KEY_ITEM_CORE_PRIMARY;
    public static final UniqueKey<ItemDescriptionRecord> KEY_ITEM_DESCRIPTION_PRIMARY = UniqueKeys0.KEY_ITEM_DESCRIPTION_PRIMARY;
    public static final UniqueKey<ItemGeneralRecord> KEY_ITEM_GENERAL_PRIMARY = UniqueKeys0.KEY_ITEM_GENERAL_PRIMARY;
    public static final UniqueKey<ItemPriceRecord> KEY_ITEM_PRICE_PRIMARY = UniqueKeys0.KEY_ITEM_PRICE_PRIMARY;
    public static final UniqueKey<ItemPriceRecord> KEY_ITEM_PRICE_IDX_UNIQUE = UniqueKeys0.KEY_ITEM_PRICE_IDX_UNIQUE;
    public static final UniqueKey<ItemVariationRecord> KEY_ITEM_VARIATION_PRIMARY = UniqueKeys0.KEY_ITEM_VARIATION_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ItemBelongsToGroupRecord, ULong> IDENTITY_ITEM_BELONGS_TO_GROUP = Internal.createIdentity(ItemBelongsToGroup.ITEM_BELONGS_TO_GROUP, ItemBelongsToGroup.ITEM_BELONGS_TO_GROUP.ID);
        public static Identity<ItemCategoryRecord, ULong> IDENTITY_ITEM_CATEGORY = Internal.createIdentity(ItemCategory.ITEM_CATEGORY, ItemCategory.ITEM_CATEGORY.ITEM_CATEGORY_ID);
        public static Identity<ItemCoreRecord, ULong> IDENTITY_ITEM_CORE = Internal.createIdentity(ItemCore.ITEM_CORE, ItemCore.ITEM_CORE.ITEM_CORE_ID);
        public static Identity<ItemDescriptionRecord, ULong> IDENTITY_ITEM_DESCRIPTION = Internal.createIdentity(ItemDescription.ITEM_DESCRIPTION, ItemDescription.ITEM_DESCRIPTION.ITEM_DESCRIPTION_ID);
        public static Identity<ItemGeneralRecord, ULong> IDENTITY_ITEM_GENERAL = Internal.createIdentity(ItemGeneral.ITEM_GENERAL, ItemGeneral.ITEM_GENERAL.ITEM_GENERAL_ID);
        public static Identity<ItemVariationRecord, ULong> IDENTITY_ITEM_VARIATION = Internal.createIdentity(ItemVariation.ITEM_VARIATION, ItemVariation.ITEM_VARIATION.ITEM_VARIATION_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ItemBelongsToGroupRecord> KEY_ITEM_BELONGS_TO_GROUP_PRIMARY = Internal.createUniqueKey(ItemBelongsToGroup.ITEM_BELONGS_TO_GROUP, "KEY_item_belongs_to_group_PRIMARY", new TableField[] { ItemBelongsToGroup.ITEM_BELONGS_TO_GROUP.ID }, true);
        public static final UniqueKey<ItemCategoryRecord> KEY_ITEM_CATEGORY_PRIMARY = Internal.createUniqueKey(ItemCategory.ITEM_CATEGORY, "KEY_item_category_PRIMARY", new TableField[] { ItemCategory.ITEM_CATEGORY.ITEM_CATEGORY_ID }, true);
        public static final UniqueKey<ItemCoreRecord> KEY_ITEM_CORE_PRIMARY = Internal.createUniqueKey(ItemCore.ITEM_CORE, "KEY_item_core_PRIMARY", new TableField[] { ItemCore.ITEM_CORE.ITEM_CORE_ID }, true);
        public static final UniqueKey<ItemDescriptionRecord> KEY_ITEM_DESCRIPTION_PRIMARY = Internal.createUniqueKey(ItemDescription.ITEM_DESCRIPTION, "KEY_item_description_PRIMARY", new TableField[] { ItemDescription.ITEM_DESCRIPTION.ITEM_DESCRIPTION_ID }, true);
        public static final UniqueKey<ItemGeneralRecord> KEY_ITEM_GENERAL_PRIMARY = Internal.createUniqueKey(ItemGeneral.ITEM_GENERAL, "KEY_item_general_PRIMARY", new TableField[] { ItemGeneral.ITEM_GENERAL.ITEM_GENERAL_ID }, true);
        public static final UniqueKey<ItemPriceRecord> KEY_ITEM_PRICE_PRIMARY = Internal.createUniqueKey(ItemPrice.ITEM_PRICE, "KEY_item_price_PRIMARY", new TableField[] { ItemPrice.ITEM_PRICE.ITEM_PRICE_ID }, true);
        public static final UniqueKey<ItemPriceRecord> KEY_ITEM_PRICE_IDX_UNIQUE = Internal.createUniqueKey(ItemPrice.ITEM_PRICE, "KEY_item_price_idx_unique", new TableField[] { ItemPrice.ITEM_PRICE.ITEM_ID, ItemPrice.ITEM_PRICE.IS_DELETED }, true);
        public static final UniqueKey<ItemVariationRecord> KEY_ITEM_VARIATION_PRIMARY = Internal.createUniqueKey(ItemVariation.ITEM_VARIATION, "KEY_item_variation_PRIMARY", new TableField[] { ItemVariation.ITEM_VARIATION.ITEM_VARIATION_ID }, true);
    }
}
