/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.commons.impl.jooq.generation;


import com.wuda.foundation.commons.impl.jooq.generation.tables.Email;
import com.wuda.foundation.commons.impl.jooq.generation.tables.Phone;
import com.wuda.foundation.commons.impl.jooq.generation.tables.PropertyKey;
import com.wuda.foundation.commons.impl.jooq.generation.tables.PropertyValue;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FoundationCommons extends SchemaImpl {

    private static final long serialVersionUID = 1292327615;

    /**
     * The reference instance of <code>foundation_commons</code>
     */
    public static final FoundationCommons FOUNDATION_COMMONS = new FoundationCommons();

    /**
     * email信息
     */
    public final Email EMAIL = Email.EMAIL;

    /**
     * 电话信息。
     */
    public final Phone PHONE = Phone.PHONE;

    /**
     * 属性的key
     */
    public final PropertyKey PROPERTY_KEY = PropertyKey.PROPERTY_KEY;

    /**
     * 属性的值
     */
    public final PropertyValue PROPERTY_VALUE = PropertyValue.PROPERTY_VALUE;

    /**
     * No further instances allowed
     */
    private FoundationCommons() {
        super("foundation_commons", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Email.EMAIL,
            Phone.PHONE,
            PropertyKey.PROPERTY_KEY,
            PropertyValue.PROPERTY_VALUE);
    }
}
