/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.user.impl.jooq.generation.tables.daos;


import com.wuda.foundation.user.impl.jooq.generation.tables.UserPhone;
import com.wuda.foundation.user.impl.jooq.generation.tables.records.UserPhoneRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * 用户的电话
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserPhoneDao extends DAOImpl<UserPhoneRecord, com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone, ULong> {

    /**
     * Create a new UserPhoneDao without any configuration
     */
    public UserPhoneDao() {
        super(UserPhone.USER_PHONE, com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone.class);
    }

    /**
     * Create a new UserPhoneDao with an attached configuration
     */
    public UserPhoneDao(Configuration configuration) {
        super(UserPhone.USER_PHONE, com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone.class, configuration);
    }

    @Override
    public ULong getId(com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(UserPhone.USER_PHONE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchById(ULong... values) {
        return fetch(UserPhone.USER_PHONE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone fetchOneById(ULong value) {
        return fetchOne(UserPhone.USER_PHONE.ID, value);
    }

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchRangeOfUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(UserPhone.USER_PHONE.USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchByUserId(ULong... values) {
        return fetch(UserPhone.USER_PHONE.USER_ID, values);
    }

    /**
     * Fetch records that have <code>phone_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchRangeOfPhoneId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(UserPhone.USER_PHONE.PHONE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>phone_id IN (values)</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchByPhoneId(ULong... values) {
        return fetch(UserPhone.USER_PHONE.PHONE_ID, values);
    }

    /**
     * Fetch records that have <code>use BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchRangeOfUse(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(UserPhone.USER_PHONE.USE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>use IN (values)</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchByUse(UByte... values) {
        return fetch(UserPhone.USER_PHONE.USE, values);
    }

    /**
     * Fetch records that have <code>state BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchRangeOfState(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(UserPhone.USER_PHONE.STATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchByState(UByte... values) {
        return fetch(UserPhone.USER_PHONE.STATE, values);
    }

    /**
     * Fetch records that have <code>description BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchRangeOfDescription(String lowerInclusive, String upperInclusive) {
        return fetchRange(UserPhone.USER_PHONE.DESCRIPTION, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchByDescription(String... values) {
        return fetch(UserPhone.USER_PHONE.DESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserPhone.USER_PHONE.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchByCreateTime(LocalDateTime... values) {
        return fetch(UserPhone.USER_PHONE.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchRangeOfCreateUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(UserPhone.USER_PHONE.CREATE_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_user_id IN (values)</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchByCreateUserId(ULong... values) {
        return fetch(UserPhone.USER_PHONE.CREATE_USER_ID, values);
    }

    /**
     * Fetch records that have <code>last_modify_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchRangeOfLastModifyTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(UserPhone.USER_PHONE.LAST_MODIFY_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modify_time IN (values)</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchByLastModifyTime(LocalDateTime... values) {
        return fetch(UserPhone.USER_PHONE.LAST_MODIFY_TIME, values);
    }

    /**
     * Fetch records that have <code>last_modify_user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchRangeOfLastModifyUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(UserPhone.USER_PHONE.LAST_MODIFY_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modify_user_id IN (values)</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchByLastModifyUserId(ULong... values) {
        return fetch(UserPhone.USER_PHONE.LAST_MODIFY_USER_ID, values);
    }

    /**
     * Fetch records that have <code>is_deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchRangeOfIsDeleted(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(UserPhone.USER_PHONE.IS_DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<com.wuda.foundation.user.impl.jooq.generation.tables.pojos.UserPhone> fetchByIsDeleted(ULong... values) {
        return fetch(UserPhone.USER_PHONE.IS_DELETED, values);
    }
}
