/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.security.impl.jooq.generation.tables.daos;


import com.wuda.foundation.security.impl.jooq.generation.tables.SubjectPermission;
import com.wuda.foundation.security.impl.jooq.generation.tables.records.SubjectPermissionRecord;

import java.time.LocalDateTime;
import java.util.List;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * subject可以代表用户，也可以代表想要访问其他资源的应用，suibject与permission的关联关系表。比如我们可以说user 【IS 
 * A】 subject
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SubjectPermissionDao extends DAOImpl<SubjectPermissionRecord, com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission, ULong> {

    /**
     * Create a new SubjectPermissionDao without any configuration
     */
    public SubjectPermissionDao() {
        super(SubjectPermission.SUBJECT_PERMISSION, com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission.class);
    }

    /**
     * Create a new SubjectPermissionDao with an attached configuration
     */
    public SubjectPermissionDao(Configuration configuration) {
        super(SubjectPermission.SUBJECT_PERMISSION, com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission.class, configuration);
    }

    @Override
    public ULong getId(com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(SubjectPermission.SUBJECT_PERMISSION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchById(ULong... values) {
        return fetch(SubjectPermission.SUBJECT_PERMISSION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission fetchOneById(ULong value) {
        return fetchOne(SubjectPermission.SUBJECT_PERMISSION.ID, value);
    }

    /**
     * Fetch records that have <code>subject_type BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchRangeOfSubjectType(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(SubjectPermission.SUBJECT_PERMISSION.SUBJECT_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>subject_type IN (values)</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchBySubjectType(UByte... values) {
        return fetch(SubjectPermission.SUBJECT_PERMISSION.SUBJECT_TYPE, values);
    }

    /**
     * Fetch records that have <code>subject_identifier BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchRangeOfSubjectIdentifier(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(SubjectPermission.SUBJECT_PERMISSION.SUBJECT_IDENTIFIER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>subject_identifier IN (values)</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchBySubjectIdentifier(ULong... values) {
        return fetch(SubjectPermission.SUBJECT_PERMISSION.SUBJECT_IDENTIFIER, values);
    }

    /**
     * Fetch records that have <code>persission_target_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchRangeOfPersissionTargetId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(SubjectPermission.SUBJECT_PERMISSION.PERSISSION_TARGET_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>persission_target_id IN (values)</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchByPersissionTargetId(ULong... values) {
        return fetch(SubjectPermission.SUBJECT_PERMISSION.PERSISSION_TARGET_ID, values);
    }

    /**
     * Fetch records that have <code>permission_action_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchRangeOfPermissionActionId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(SubjectPermission.SUBJECT_PERMISSION.PERMISSION_ACTION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>permission_action_id IN (values)</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchByPermissionActionId(ULong... values) {
        return fetch(SubjectPermission.SUBJECT_PERMISSION.PERMISSION_ACTION_ID, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(SubjectPermission.SUBJECT_PERMISSION.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchByCreateTime(LocalDateTime... values) {
        return fetch(SubjectPermission.SUBJECT_PERMISSION.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchRangeOfCreateUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(SubjectPermission.SUBJECT_PERMISSION.CREATE_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_user_id IN (values)</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchByCreateUserId(ULong... values) {
        return fetch(SubjectPermission.SUBJECT_PERMISSION.CREATE_USER_ID, values);
    }

    /**
     * Fetch records that have <code>is_deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchRangeOfIsDeleted(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(SubjectPermission.SUBJECT_PERMISSION.IS_DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<com.wuda.foundation.security.impl.jooq.generation.tables.pojos.SubjectPermission> fetchByIsDeleted(ULong... values) {
        return fetch(SubjectPermission.SUBJECT_PERMISSION.IS_DELETED, values);
    }
}
