/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.user.impl.jooq.generation.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * 用户所属的组
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserBelongsToGroupCore implements Serializable {

    private static final long serialVersionUID = 739442725;

    private ULong         userBelongsToGroupCoreId;
    private ULong         userBelongsToGroupId;
    private ULong         userId;
    private UShort        groupType;
    private ULong         groupIdentifier;
    private LocalDateTime createTime;
    private ULong         createUserId;
    private LocalDateTime lastModifyTime;
    private ULong         lastModifyUserId;
    private ULong         isDeleted;

    public UserBelongsToGroupCore() {}

    public UserBelongsToGroupCore(UserBelongsToGroupCore value) {
        this.userBelongsToGroupCoreId = value.userBelongsToGroupCoreId;
        this.userBelongsToGroupId = value.userBelongsToGroupId;
        this.userId = value.userId;
        this.groupType = value.groupType;
        this.groupIdentifier = value.groupIdentifier;
        this.createTime = value.createTime;
        this.createUserId = value.createUserId;
        this.lastModifyTime = value.lastModifyTime;
        this.lastModifyUserId = value.lastModifyUserId;
        this.isDeleted = value.isDeleted;
    }

    public UserBelongsToGroupCore(
        ULong         userBelongsToGroupCoreId,
        ULong         userBelongsToGroupId,
        ULong         userId,
        UShort        groupType,
        ULong         groupIdentifier,
        LocalDateTime createTime,
        ULong         createUserId,
        LocalDateTime lastModifyTime,
        ULong         lastModifyUserId,
        ULong         isDeleted
    ) {
        this.userBelongsToGroupCoreId = userBelongsToGroupCoreId;
        this.userBelongsToGroupId = userBelongsToGroupId;
        this.userId = userId;
        this.groupType = groupType;
        this.groupIdentifier = groupIdentifier;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.lastModifyTime = lastModifyTime;
        this.lastModifyUserId = lastModifyUserId;
        this.isDeleted = isDeleted;
    }

    public ULong getUserBelongsToGroupCoreId() {
        return this.userBelongsToGroupCoreId;
    }

    public void setUserBelongsToGroupCoreId(ULong userBelongsToGroupCoreId) {
        this.userBelongsToGroupCoreId = userBelongsToGroupCoreId;
    }

    public ULong getUserBelongsToGroupId() {
        return this.userBelongsToGroupId;
    }

    public void setUserBelongsToGroupId(ULong userBelongsToGroupId) {
        this.userBelongsToGroupId = userBelongsToGroupId;
    }

    public ULong getUserId() {
        return this.userId;
    }

    public void setUserId(ULong userId) {
        this.userId = userId;
    }

    public UShort getGroupType() {
        return this.groupType;
    }

    public void setGroupType(UShort groupType) {
        this.groupType = groupType;
    }

    public ULong getGroupIdentifier() {
        return this.groupIdentifier;
    }

    public void setGroupIdentifier(ULong groupIdentifier) {
        this.groupIdentifier = groupIdentifier;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public ULong getCreateUserId() {
        return this.createUserId;
    }

    public void setCreateUserId(ULong createUserId) {
        this.createUserId = createUserId;
    }

    public LocalDateTime getLastModifyTime() {
        return this.lastModifyTime;
    }

    public void setLastModifyTime(LocalDateTime lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    public ULong getLastModifyUserId() {
        return this.lastModifyUserId;
    }

    public void setLastModifyUserId(ULong lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    public ULong getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(ULong isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserBelongsToGroupCore (");

        sb.append(userBelongsToGroupCoreId);
        sb.append(", ").append(userBelongsToGroupId);
        sb.append(", ").append(userId);
        sb.append(", ").append(groupType);
        sb.append(", ").append(groupIdentifier);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createUserId);
        sb.append(", ").append(lastModifyTime);
        sb.append(", ").append(lastModifyUserId);
        sb.append(", ").append(isDeleted);

        sb.append(")");
        return sb.toString();
    }
}
