/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.jooq.code.generation.notification.tables.daos;


import com.wuda.foundation.jooq.code.generation.notification.tables.NotificationDefinitionObserver;
import com.wuda.foundation.jooq.code.generation.notification.tables.records.NotificationDefinitionObserverRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;

import java.time.LocalDateTime;
import java.util.List;


/**
 * 定义通知的观察者，用于接收或者查看通知
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationDefinitionObserverDao extends DAOImpl<NotificationDefinitionObserverRecord, com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver, ULong> {

    /**
     * Create a new NotificationDefinitionObserverDao without any configuration
     */
    public NotificationDefinitionObserverDao() {
        super(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER, com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver.class);
    }

    /**
     * Create a new NotificationDefinitionObserverDao with an attached configuration
     */
    public NotificationDefinitionObserverDao(Configuration configuration) {
        super(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER, com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver.class, configuration);
    }

    @Override
    public ULong getId(com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver object) {
        return object.getNotificationDefinitionObserverId();
    }

    /**
     * Fetch records that have <code>notification_definition_observer_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchRangeOfNotificationDefinitionObserverId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.NOTIFICATION_DEFINITION_OBSERVER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>notification_definition_observer_id IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchByNotificationDefinitionObserverId(ULong... values) {
        return fetch(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.NOTIFICATION_DEFINITION_OBSERVER_ID, values);
    }

    /**
     * Fetch a unique record that has <code>notification_definition_observer_id = value</code>
     */
    public com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver fetchOneByNotificationDefinitionObserverId(ULong value) {
        return fetchOne(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.NOTIFICATION_DEFINITION_OBSERVER_ID, value);
    }

    /**
     * Fetch records that have <code>notification_definition_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchRangeOfNotificationDefinitionId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.NOTIFICATION_DEFINITION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>notification_definition_id IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchByNotificationDefinitionId(ULong... values) {
        return fetch(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.NOTIFICATION_DEFINITION_ID, values);
    }

    /**
     * Fetch records that have <code>notification_definition_send_method_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchRangeOfNotificationDefinitionSendMethodId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.NOTIFICATION_DEFINITION_SEND_METHOD_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>notification_definition_send_method_id IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchByNotificationDefinitionSendMethodId(ULong... values) {
        return fetch(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.NOTIFICATION_DEFINITION_SEND_METHOD_ID, values);
    }

    /**
     * Fetch records that have <code>observer_type BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchRangeOfObserverType(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.OBSERVER_TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>observer_type IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchByObserverType(UByte... values) {
        return fetch(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.OBSERVER_TYPE, values);
    }

    /**
     * Fetch records that have <code>observer_identifier BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchRangeOfObserverIdentifier(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.OBSERVER_IDENTIFIER, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>observer_identifier IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchByObserverIdentifier(ULong... values) {
        return fetch(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.OBSERVER_IDENTIFIER, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchByCreateTime(LocalDateTime... values) {
        return fetch(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchRangeOfCreateUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.CREATE_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_user_id IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchByCreateUserId(ULong... values) {
        return fetch(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.CREATE_USER_ID, values);
    }

    /**
     * Fetch records that have <code>last_modify_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchRangeOfLastModifyTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.LAST_MODIFY_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modify_time IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchByLastModifyTime(LocalDateTime... values) {
        return fetch(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.LAST_MODIFY_TIME, values);
    }

    /**
     * Fetch records that have <code>last_modify_user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchRangeOfLastModifyUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.LAST_MODIFY_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modify_user_id IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchByLastModifyUserId(ULong... values) {
        return fetch(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.LAST_MODIFY_USER_ID, values);
    }

    /**
     * Fetch records that have <code>is_deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchRangeOfIsDeleted(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.IS_DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.notification.tables.pojos.NotificationDefinitionObserver> fetchByIsDeleted(ULong... values) {
        return fetch(NotificationDefinitionObserver.NOTIFICATION_DEFINITION_OBSERVER.IS_DELETED, values);
    }
}
