/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.jooq.code.generation.item.tables.daos;


import com.wuda.foundation.jooq.code.generation.item.tables.ItemCore;
import com.wuda.foundation.jooq.code.generation.item.tables.records.ItemCoreRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;

import java.time.LocalDateTime;
import java.util.List;


/**
 * 物品核心信息，代表所有的物品，之前有把用户ID放进来，表示该物品所属的用户，但是考虑到如果有子账号的情况，物品难道属于这个子账号所属的用户吗？而且记录了创建人用户ID，考虑这两个因素，因此不设置用户ID列
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemCoreDao extends DAOImpl<ItemCoreRecord, com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore, ULong> {

    /**
     * Create a new ItemCoreDao without any configuration
     */
    public ItemCoreDao() {
        super(ItemCore.ITEM_CORE, com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore.class);
    }

    /**
     * Create a new ItemCoreDao with an attached configuration
     */
    public ItemCoreDao(Configuration configuration) {
        super(ItemCore.ITEM_CORE, com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore.class, configuration);
    }

    @Override
    public ULong getId(com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore object) {
        return object.getItemCoreId();
    }

    /**
     * Fetch records that have <code>item_core_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchRangeOfItemCoreId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(ItemCore.ITEM_CORE.ITEM_CORE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>item_core_id IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchByItemCoreId(ULong... values) {
        return fetch(ItemCore.ITEM_CORE.ITEM_CORE_ID, values);
    }

    /**
     * Fetch a unique record that has <code>item_core_id = value</code>
     */
    public com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore fetchOneByItemCoreId(ULong value) {
        return fetchOne(ItemCore.ITEM_CORE.ITEM_CORE_ID, value);
    }

    /**
     * Fetch records that have <code>item_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchRangeOfItemId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(ItemCore.ITEM_CORE.ITEM_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>item_id IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchByItemId(ULong... values) {
        return fetch(ItemCore.ITEM_CORE.ITEM_ID, values);
    }

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchRangeOfType(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(ItemCore.ITEM_CORE.TYPE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchByType(UByte... values) {
        return fetch(ItemCore.ITEM_CORE.TYPE, values);
    }

    /**
     * Fetch records that have <code>state BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchRangeOfState(UByte lowerInclusive, UByte upperInclusive) {
        return fetchRange(ItemCore.ITEM_CORE.STATE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>state IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchByState(UByte... values) {
        return fetch(ItemCore.ITEM_CORE.STATE, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ItemCore.ITEM_CORE.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchByCreateTime(LocalDateTime... values) {
        return fetch(ItemCore.ITEM_CORE.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchRangeOfCreateUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(ItemCore.ITEM_CORE.CREATE_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_user_id IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchByCreateUserId(ULong... values) {
        return fetch(ItemCore.ITEM_CORE.CREATE_USER_ID, values);
    }

    /**
     * Fetch records that have <code>last_modify_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchRangeOfLastModifyTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(ItemCore.ITEM_CORE.LAST_MODIFY_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modify_time IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchByLastModifyTime(LocalDateTime... values) {
        return fetch(ItemCore.ITEM_CORE.LAST_MODIFY_TIME, values);
    }

    /**
     * Fetch records that have <code>last_modify_user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchRangeOfLastModifyUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(ItemCore.ITEM_CORE.LAST_MODIFY_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modify_user_id IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchByLastModifyUserId(ULong... values) {
        return fetch(ItemCore.ITEM_CORE.LAST_MODIFY_USER_ID, values);
    }

    /**
     * Fetch records that have <code>is_deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchRangeOfIsDeleted(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(ItemCore.ITEM_CORE.IS_DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<com.wuda.foundation.jooq.code.generation.item.tables.pojos.ItemCore> fetchByIsDeleted(ULong... values) {
        return fetch(ItemCore.ITEM_CORE.IS_DELETED, values);
    }
}
