/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.core.notification.impl.jooq.generation.tables.daos;


import com.wuda.foundation.core.notification.impl.jooq.generation.tables.NotificationInstanceContent;
import com.wuda.foundation.core.notification.impl.jooq.generation.tables.records.NotificationInstanceContentRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;

import java.time.LocalDateTime;
import java.util.List;


/**
 * 代表一条实际已经发送的通知。通知模块的设计，不局限于发给用户，或者从用户发出来，任何实体都可以发送和接收，比如service A可以发送给service 
 * B，因此会有receiver type和sender type的设计。同样的内容，可以通过多种方式发送，比如通过邮件，短信发送同样的内容，因此发送方式不放到这个表中，这样的好处是不同的发送方式可以指向（共享）同一个通知。
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationInstanceContentDao extends DAOImpl<NotificationInstanceContentRecord, com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent, ULong> {

    /**
     * Create a new NotificationInstanceContentDao without any configuration
     */
    public NotificationInstanceContentDao() {
        super(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT, com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent.class);
    }

    /**
     * Create a new NotificationInstanceContentDao with an attached configuration
     */
    public NotificationInstanceContentDao(Configuration configuration) {
        super(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT, com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent.class, configuration);
    }

    @Override
    public ULong getId(com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent object) {
        return object.getNotificationInstanceContentId();
    }

    /**
     * Fetch records that have <code>notification_instance_content_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchRangeOfNotificationInstanceContentId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.NOTIFICATION_INSTANCE_CONTENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>notification_instance_content_id IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchByNotificationInstanceContentId(ULong... values) {
        return fetch(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.NOTIFICATION_INSTANCE_CONTENT_ID, values);
    }

    /**
     * Fetch a unique record that has <code>notification_instance_content_id = value</code>
     */
    public com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent fetchOneByNotificationInstanceContentId(ULong value) {
        return fetchOne(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.NOTIFICATION_INSTANCE_CONTENT_ID, value);
    }

    /**
     * Fetch records that have <code>notification_definition_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchRangeOfNotificationDefinitionId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.NOTIFICATION_DEFINITION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>notification_definition_id IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchByNotificationDefinitionId(ULong... values) {
        return fetch(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.NOTIFICATION_DEFINITION_ID, values);
    }

    /**
     * Fetch records that have <code>notification_definition_send_method_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchRangeOfNotificationDefinitionSendMethodId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.NOTIFICATION_DEFINITION_SEND_METHOD_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>notification_definition_send_method_id IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchByNotificationDefinitionSendMethodId(ULong... values) {
        return fetch(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.NOTIFICATION_DEFINITION_SEND_METHOD_ID, values);
    }

    /**
     * Fetch records that have <code>notification_definition_content_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchRangeOfNotificationDefinitionContentId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.NOTIFICATION_DEFINITION_CONTENT_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>notification_definition_content_id IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchByNotificationDefinitionContentId(ULong... values) {
        return fetch(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.NOTIFICATION_DEFINITION_CONTENT_ID, values);
    }

    /**
     * Fetch records that have <code>notification_category_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchRangeOfNotificationCategoryId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.NOTIFICATION_CATEGORY_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>notification_category_id IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchByNotificationCategoryId(ULong... values) {
        return fetch(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.NOTIFICATION_CATEGORY_ID, values);
    }

    /**
     * Fetch records that have <code>title BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchRangeOfTitle(String lowerInclusive, String upperInclusive) {
        return fetchRange(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.TITLE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>title IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchByTitle(String... values) {
        return fetch(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.TITLE, values);
    }

    /**
     * Fetch records that have <code>body BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchRangeOfBody(String lowerInclusive, String upperInclusive) {
        return fetchRange(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.BODY, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>body IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchByBody(String... values) {
        return fetch(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.BODY, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchByCreateTime(LocalDateTime... values) {
        return fetch(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchRangeOfCreateUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.CREATE_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_user_id IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchByCreateUserId(ULong... values) {
        return fetch(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.CREATE_USER_ID, values);
    }

    /**
     * Fetch records that have <code>last_modify_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchRangeOfLastModifyTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.LAST_MODIFY_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modify_time IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchByLastModifyTime(LocalDateTime... values) {
        return fetch(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.LAST_MODIFY_TIME, values);
    }

    /**
     * Fetch records that have <code>last_modify_user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchRangeOfLastModifyUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.LAST_MODIFY_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modify_user_id IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchByLastModifyUserId(ULong... values) {
        return fetch(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.LAST_MODIFY_USER_ID, values);
    }

    /**
     * Fetch records that have <code>is_deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchRangeOfIsDeleted(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.IS_DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationInstanceContent> fetchByIsDeleted(ULong... values) {
        return fetch(NotificationInstanceContent.NOTIFICATION_INSTANCE_CONTENT.IS_DELETED, values);
    }
}
