/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.core.notification.impl.jooq.generation.tables.daos;


import com.wuda.foundation.core.notification.impl.jooq.generation.tables.NotificationDifinitionGroupRelation;
import com.wuda.foundation.core.notification.impl.jooq.generation.tables.records.NotificationDifinitionGroupRelationRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.jooq.types.ULong;

import java.time.LocalDateTime;
import java.util.List;


/**
 * 通知定义所属的组
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NotificationDifinitionGroupRelationDao extends DAOImpl<NotificationDifinitionGroupRelationRecord, com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation, ULong> {

    /**
     * Create a new NotificationDifinitionGroupRelationDao without any configuration
     */
    public NotificationDifinitionGroupRelationDao() {
        super(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION, com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation.class);
    }

    /**
     * Create a new NotificationDifinitionGroupRelationDao with an attached configuration
     */
    public NotificationDifinitionGroupRelationDao(Configuration configuration) {
        super(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION, com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation.class, configuration);
    }

    @Override
    public ULong getId(com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchRangeOfId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchById(ULong... values) {
        return fetch(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation fetchOneById(ULong value) {
        return fetchOne(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.ID, value);
    }

    /**
     * Fetch records that have <code>notification_difinition_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchRangeOfNotificationDifinitionId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.NOTIFICATION_DIFINITION_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>notification_difinition_id IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchByNotificationDifinitionId(ULong... values) {
        return fetch(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.NOTIFICATION_DIFINITION_ID, values);
    }

    /**
     * Fetch records that have <code>group_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchRangeOfGroupId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.GROUP_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>group_id IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchByGroupId(ULong... values) {
        return fetch(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.GROUP_ID, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchByCreateTime(LocalDateTime... values) {
        return fetch(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>create_user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchRangeOfCreateUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.CREATE_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_user_id IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchByCreateUserId(ULong... values) {
        return fetch(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.CREATE_USER_ID, values);
    }

    /**
     * Fetch records that have <code>last_modify_time BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchRangeOfLastModifyTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.LAST_MODIFY_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modify_time IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchByLastModifyTime(LocalDateTime... values) {
        return fetch(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.LAST_MODIFY_TIME, values);
    }

    /**
     * Fetch records that have <code>last_modify_user_id BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchRangeOfLastModifyUserId(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.LAST_MODIFY_USER_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>last_modify_user_id IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchByLastModifyUserId(ULong... values) {
        return fetch(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.LAST_MODIFY_USER_ID, values);
    }

    /**
     * Fetch records that have <code>is_deleted BETWEEN lowerInclusive AND upperInclusive</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchRangeOfIsDeleted(ULong lowerInclusive, ULong upperInclusive) {
        return fetchRange(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.IS_DELETED, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>is_deleted IN (values)</code>
     */
    public List<com.wuda.foundation.core.notification.impl.jooq.generation.tables.pojos.NotificationDifinitionGroupRelation> fetchByIsDeleted(ULong... values) {
        return fetch(NotificationDifinitionGroupRelation.NOTIFICATION_DIFINITION_GROUP_RELATION.IS_DELETED, values);
    }
}
