/*
 * This file is generated by jOOQ.
 */
package com.wuda.foundation.jooq.code.generation.user.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import org.jooq.types.ULong;
import org.jooq.types.UShort;


/**
 * 用户在所属的组中的角色
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserBelongsToGroupRole implements Serializable {

    private static final long serialVersionUID = 311255835;

    private ULong         id;
    private ULong         userId;
    private UShort        groupType;
    private ULong         groupIdentifier;
    private ULong         permissionRoleId;
    private LocalDateTime createTime;
    private ULong         createUserId;
    private LocalDateTime lastModifyTime;
    private ULong         lastModifyUserId;
    private ULong         isDeleted;

    public UserBelongsToGroupRole() {}

    public UserBelongsToGroupRole(UserBelongsToGroupRole value) {
        this.id = value.id;
        this.userId = value.userId;
        this.groupType = value.groupType;
        this.groupIdentifier = value.groupIdentifier;
        this.permissionRoleId = value.permissionRoleId;
        this.createTime = value.createTime;
        this.createUserId = value.createUserId;
        this.lastModifyTime = value.lastModifyTime;
        this.lastModifyUserId = value.lastModifyUserId;
        this.isDeleted = value.isDeleted;
    }

    public UserBelongsToGroupRole(
        ULong         id,
        ULong         userId,
        UShort        groupType,
        ULong         groupIdentifier,
        ULong         permissionRoleId,
        LocalDateTime createTime,
        ULong         createUserId,
        LocalDateTime lastModifyTime,
        ULong         lastModifyUserId,
        ULong         isDeleted
    ) {
        this.id = id;
        this.userId = userId;
        this.groupType = groupType;
        this.groupIdentifier = groupIdentifier;
        this.permissionRoleId = permissionRoleId;
        this.createTime = createTime;
        this.createUserId = createUserId;
        this.lastModifyTime = lastModifyTime;
        this.lastModifyUserId = lastModifyUserId;
        this.isDeleted = isDeleted;
    }

    public ULong getId() {
        return this.id;
    }

    public void setId(ULong id) {
        this.id = id;
    }

    public ULong getUserId() {
        return this.userId;
    }

    public void setUserId(ULong userId) {
        this.userId = userId;
    }

    public UShort getGroupType() {
        return this.groupType;
    }

    public void setGroupType(UShort groupType) {
        this.groupType = groupType;
    }

    public ULong getGroupIdentifier() {
        return this.groupIdentifier;
    }

    public void setGroupIdentifier(ULong groupIdentifier) {
        this.groupIdentifier = groupIdentifier;
    }

    public ULong getPermissionRoleId() {
        return this.permissionRoleId;
    }

    public void setPermissionRoleId(ULong permissionRoleId) {
        this.permissionRoleId = permissionRoleId;
    }

    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    public ULong getCreateUserId() {
        return this.createUserId;
    }

    public void setCreateUserId(ULong createUserId) {
        this.createUserId = createUserId;
    }

    public LocalDateTime getLastModifyTime() {
        return this.lastModifyTime;
    }

    public void setLastModifyTime(LocalDateTime lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }

    public ULong getLastModifyUserId() {
        return this.lastModifyUserId;
    }

    public void setLastModifyUserId(ULong lastModifyUserId) {
        this.lastModifyUserId = lastModifyUserId;
    }

    public ULong getIsDeleted() {
        return this.isDeleted;
    }

    public void setIsDeleted(ULong isDeleted) {
        this.isDeleted = isDeleted;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserBelongsToGroupRole (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(groupType);
        sb.append(", ").append(groupIdentifier);
        sb.append(", ").append(permissionRoleId);
        sb.append(", ").append(createTime);
        sb.append(", ").append(createUserId);
        sb.append(", ").append(lastModifyTime);
        sb.append(", ").append(lastModifyUserId);
        sb.append(", ").append(isDeleted);

        sb.append(")");
        return sb.toString();
    }
}
